version: '3'

name: channel_helper_chatbot
services:

  channel_helper_bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: channel_helper_bot
    container_name: channel_helper_bot
    env_file:
      - .env
    volumes:
      - ${LOGS_PATH}:${LOGS_PATH}
    restart: always
    tty: True
    working_dir: /bot
